### ISSUE TITLE
Background playback and mini player

### ISSUE THREAD

**Issue by Nizami20052022** [VueTubeApp/VueTube#397] opened 2022-06-23 10:59 UTC
### Describe your 
When you press the back button while playing a video, the video stops, but the video must continue at the bottom. This program does not support playback in the background and in instant window mode.
![Screenshot_20220623-145851_LibreTube](https://user-images.githubusercontent.com/104249296/175283850-fd52a37a-a457-4644-b9ae-b64c4b3463a2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 404-Program-not-found** [comment] 2022-06-23 11:35
this is a duplicate of #52

**Closed by 404-Program-not-found** 2022-06-23 11:35 UTC
Labels: feature request

**Comment by Nizami20052022** [comment] 2022-06-23 11:46
Confirm the Azerbaijani translation.
